microsoft/ethr

- plt_linux.go
- plt_windows.go
- serverui.go
- ui.go
On East Asian locales like CJK, interface name have multi-byte letters. (ex: ローカルエリア接続) And also, Windows command prompt on CJK draw strange characters which have different withds to non-CJK console.
This change fix location to draw multi-byte letter. And change to use ASCII letters for borders on CJK.
> Fix multibyte ui

- .gitignore
Small fix to ignore all files without extension - like the output of `go build` for non-Windows.
> Add files without extension to .gitigore

- README.md
Using "```bash" in markdown results in bash keywords being high-lightened (coloured) like "test" or "for". However, the README is not showing bash code, but shell input and output.
> Disable incorrect bash syntax highlighting for shell input/output

- server.go
Hi, I found two little error messages mistakes.
that doesn’t refer to collect port numbers. 
Both of them refers to `tcpLatencyPort`. 
It should be `tcpXXXPort` in `runTcpXXXServer()`
> fix port error messages on server

- ethr.go
I found the mismatch types of durationStr in printf
```
$ go test ./...
./ethr.go:115: Printf format %s has arg durationStr of wrong type *string
```
I fixed this PR. please check it.
> fix wrong type durationStr in ethr.go

- server.go
#40 
i fix go vet failed which sweep unreachable code.
before:
```
$ go vet ./...
./server.go:39: unreachable code
```
after:
```
$ go vet ./...
$
```
go vet command in details, please read docs 
https://golang.org/cmd/vet/
> Move stopStatsTimer in defer runServer #40

- plt_darwin.go
The build for darwin is currently broken due to missing `getTCPStats` function, that exists with older `getTcpStats` name.
This PR renames the function to fix the build.
> Fix wrong function name for darwin build

- plt_darwin.go
This way CGO isn't required. The struct was generated using the same
script that the Go teams uses in golang.org/x/sys/unix, which uses `cgo
-godefs` (see https://golang.org/cmd/cgo/#hdr-Go_references_to_C).
Since we're not calling any C functions but rather using a struct, the
struct can be defined in Go and the bytes can be read into the Go
struct, ``cgo -godefs`` handles the difference in alignment between Go and C.
> darwin: gen struct from C for TCP stats

- ethr.go
After #50 `ethr` can't be used without passing custom ports. This should fix that
> Fix ethr when using default ports

- session.go
When compiling ethr for a x86-32 system (i.e. windows/386), running ethr as client throws this runtime error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x401ebc]
goroutine 14 [running]:
runtime/internal/atomic.Xadd64(0x11864824, 0x3e80, 0x0, 0x3e80, 0x3e80)
C:/Go/src/runtime/internal/atomic/asm_386.s:102 +0xc
main.runTCPBandwidthTest.func1(0x1180a0d0, 0xc, 0x118362c0, 0x118d4000, 0x3e80, 0x3e80)
D:/ssambi/Documents/GitHub/ethr/client.go:202 +0x464
created by main.runTCPBandwidthTest
D:/ssambi/Documents/GitHub/ethr/client.go:169 +0x142
```
It's caused by data alignment, so moving the variable used in atomic instruction will solve.
See:
- https://github.com/golang/go/issues/5278
- …
> fix a runtime error thrown when running on x86-32

- ethr.go
- session.go
- xclient.go
- xserver.go
Add support for external mode server. This also enables support for running Ethr behind a load balancer. In this mode, you can run server behind a load balancer on multiple nodes using ethr -s -m x and then use a single client to send traffic to all these servers, using ethr -c <server> -m x -n 64
This would create 64 sessions and start sending traffic. A load balancer in the middle can distribute these to different nodes running ethr.
> Load balancer support via External Mode

- README.md
- client.go
- ethr.go
- server.go
Issue: #58 
I wanted to confirm that for http tests, only client request and server response latency is calculated at client side, which happens in this pull request.
We shouldn't do for server request and client response (as it doesn't make sense for http).
> Added support for HTTP latency testing

- client.go
In `establishSession()` if the `ethrMsg` returned from server is not `EthrAck` of type, test should be stopped with error but it went down to next procedure, which caused SEGV due to the access to a member of nil pointer(`ethrMsg.Ack.Cert`).
Just by adding `return nil, err` it can be avoided and the program finishes with expected error message.
```
ethr -c 100.100.100.210
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c907d]
goroutine 1 [running]:
main.establishSession(0x100000000, 0x3e8000000001, 0x3e8, 0xc000d66000, 0x11, 0xc00009e070, 0x80eae0, 0xc000d406e0)
/mnt/c/Users/ykura/dev/ethr/client.go:79 +0x5ed
main.runClient(0x100000000, 0x3e8000000001, 0x3e8, 0x2540be400, 0x0, 0x7ffc341a8770, 0xf) …
```
> Fix error handling in establishSession()

- internal/stats/linux.go
Added a sanity check for the /proc/net/dev file for linux machines as formats may differ. This is a temporary/dirty fix and the code needs to be changed to handle differing formats/OS variants more elegantly if possible.
Issue #91
> Added linux sanity checking for /proc/net/dev

- internal/stats/linux.go
Fixes a bug for Linux-based machines which incorrectly parses /proc/net/dev
> Fix bug incorrectly parsing /proc/net/dev

- client.go
- ethr.go
- server.go
* Remove hardcoded buffer of 1 from latency test on server and client. We noticed that during latency tests, the buffer size was hardcoded to 1. That made us unable to test latency on certain packet sizes.
> Remove hardcoded buffer of 1 from latency test on server and client(#1)

- internal/stats/darwin.go
Because res was initialized with a size of len(ifs), the UI displayed "empty" interfaces.
> Ignore interfaces that are down

- utils/utils.go
When testing low latency lines, 2 digits precision is not enough.
By displaying 3 digits after decimal point, ethr latency test helps me to find out some of our switch would incur about 40us latency.
> Print 3 digits after decimal point for duration.

- client.go
- xclient.go
- xserver.go
This PR fixes the case where `os.Kill` was being tried to be handled. But [os.Kill](https://golang.org/pkg/os/#Signal) is basically `syscall.SIGKILL` and `SIGKILL` can't be captured/ handled. Previously it was working because when a `SIGINT` (Interrupt) arrived, the control was given to the `case os.Kill` using `fallthrough` which was present in the `case os.Interrupt` of `switch` block which is wrong.
Also, renamed `handleCtrlC` to `handleInterrupt` because it's addresses the functionality better. `CtrlC` is just a key combination to generate program interrupts (or `SIGINT`) and there could be other possible ways (and more appropriate) to generate the same signals (eg. using `kill -2`).
Ref: [SIGTERM, SIGINT (GNU's doc on signals)](https://www.gnu.org/software/libc/manual/html_node/Termin …
> Fix handling of interrupt

- Dockerfile
With the migration to Go Modules, one should avoid the use of the "go get".
> Use "go build" instead of "go get"

- go.mod
- go.sum
Update the packages to their latest compatible versions. Also ran `go mod tidy` which removed the unused `github.com/pkg/errors` package.
> Update compatible modules to their latest versions
